#!/bin/bash

# bash helper script to pull latest version of Wordsmith jquery plugin

# get the latest version of wordsmith.js from master
wget --output-document downloads/wordsmith.js https://raw.github.com/Wordsmith/wordsmith-plugin/master/wordsmith.js

# minify, update version numbers
./postupdate
